config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :edit, :show, :update, :new, :create, :destroy]


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios do
    put :sort, on: :collection
  end
  
  get 'angular-items', to: 'portfolios#angular'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech_news', to: 'pages#tech_news'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end


  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
  
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id

  belongs_to :topic

  has_many :comments, dependent: :destroy

  def self.by_updated_at
    order("updated_at DESC")
  end
  def self.by_created_at
    order("created_at DESC")
  end

  def self.published
     where(status: :published)
  end
  def self.draft
     where(status: :draft)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_topics
  before_action :set_sidebar_topics
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs_published = Blog.published.by_created_at.page(params[:page]).per(5)
    @blogs_all = Blog.by_created_at.page(params[:page]).per(5)

    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: 'You are not authorized to access this page!'
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    # byebug
    if @blog.draft? 
      @blog.published!
    else
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has beend updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

     def set_topics
      @topics = Topic.all
    end

    def set_sidebar_topics
      if logged_in?(:site_admin) 
        @sidebar_topics = Topic.with_blogs
      else
        @sidebar_topics = Topic.with_blogs_published
      end
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper

  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 40
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code,language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)
    options = {
    fenced_code_blocks: true,
    no_intra_emphasis: true,
    autolink: true,
    lax_html_blocks: true
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

end

app/views/blogs/_blog.html.erb
  <div class="blog-post">
    <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
    <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
    <p class="blog-post-meta">Topic: <%= blog.topic.title %> </p>


    <% if logged_in?(:site_admin) %>
      <% if blog.draft? %>
        <% tog_status = "Published" %>
        <% button = "primary" %>
      <% else %>
        <% tog_status = "Draft" %>
        <% button = "info" %>
      <% end %>
        <p class="blog-post-meta">
          <%= link_to "Change Status to #{tog_status}", toggle_status_blog_path(blog), class: "btn btn-#{button}" %>
          <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-warning' %>
          <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </p>
    <% end %>

    <p><%= markdown blog.body %></p>

  </div>  

  

app/views/blogs/_blog_title.html.erb
<div class="blog-masthead">
  <div class="container">
    <div class="row">
      
        <div class="col-sm-8">
        <nav class="nav blog-nav">
          <%= render "shared/nav", style: 'nav-link' %>
        </nav>
        </div>   
        
        <div class="col-sm-4">
        <nav class="nav blog-nav">
          <%= login_helper("nav-link") %>
        </nav>
        </div>
    
    </div>
  </div>
</div>
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Blogs</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alerts(error) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', rows: 15, placeholder: "Content" %>
  </div>
  
 
  <div class="topic-selection form-control">
    <%= f.label :topic_id %>
    <%= f.collection_select(:topic_id, Topic.all, :id, :title, {selected: blog.topic_id, include_blank: false}, class: 'form-control') %>
    <%= link_to 'Edit Topics', topics_path %>
  </div>

  <div class="form-group">
    <%= f.radio_button :status, 'draft' %>
    <%= f.label :status, 'Draft' %>
    <%= f.radio_button :status, 'published' %>
    <%= f.label :status, 'Published' %>
  </div>
  
  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
    <%= link_to 'Cancel and Back to Overview', blogs_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

app/views/blogs/index.html.erb
<% if logged_in?(:site_admin) %>
<%  blogs = @blogs_all %>
<% else %>
<% blogs = @blogs_published %>
<% end %>



<%= link_to 'Wirte a new Blog', new_blog_path if logged_in?(:site_admin)%>
<%= paginate blogs %>
<%= render blogs, layout: 'blog' %>
<%= paginate blogs %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <italics>Topic: <%= Topic.find(@blog.topic_id).title %> </italics>
</p>



<p>
  <strong>Body:</strong>
  <%= markdown @blog.body %>
</p>

<%= link_to 'Edit Blogpost', edit_blog_path(@blog), class: 'btn btn-warning' if logged_in?(:site_admin)%> 
<%= link_to 'Back to Overview', blogs_path, class: 'btn btn-primary' %> 

<%= render "comments/comment_form" %>
<!-- Start Display Comments -->
<div id="comments" data-blog-id="<%= @blog.id %>">
  <%= render @blog.comments %>
</div>


<%= link_to 'Back to Overview', blogs_path, class: 'btn btn-primary' %> 