config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :edit, :show, :update, :new, :create, :destroy]


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios do
    put :sort, on: :collection
  end
  
  get 'angular-items', to: 'portfolios#angular'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech_news', to: 'pages#tech_news'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end


  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
  
end

app/models/topic.rb
class Topic < ApplicationRecord

  validates_presence_of :title

  has_many :blogs

  def self.sort_by_id
    order("id ASC")
  end

  def self.with_blogs
    includes(:blogs).where.not(blogs: {id: nil})
  end

  def self.with_blogs_published
    includes(:blogs).where.not(blogs: {id: nil} && {status: 'draft'})
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:edit, :update, :destroy, :show]
  before_action :set_topics, only: [:index, :update]
  before_action :set_sidebar_topics
  
  layout "blog"

  def index
  end

  def new
    @topic = Topic.new
  end

  def show
  if logged_in?(:site_admin) 
      @topic_blogs = @topic.blogs.by_created_at.page(params[:page]).per(5)  
    else
      @topic_blogs = @topic.blogs.published.by_created_at.page(params[:page]).per(5)
    end

  end

  def create
    @topic = Topic.new(topic_params)
      if @topic.save
        redirect_to topics_path, notice: 'Topic was successfully created.'
      else
        redirect_to topics_path, notice: 'Topic could not be created.'
        
      end
  end

  def edit
  end

  def update
      if @topic.update(topic_params)
        redirect_to topics_path, notice: 'Topic was successfully updated.'
      else
        redirect_to topics_path, notice: 'Topic could not be updated.'
        
      end
  end

  def destroy
    @topic.blogs.each do |b|
      b.update!(topic_id: 1)
    end
    @topic.destroy
    redirect_to topics_path, notice: 'Blog was successfully destroyed.'
  end

private
    # Use callbacks to share common setup or constraints between actions.
  

    def set_topic
      @topic = Topic.find(params[:id])
    end

    def set_topics
      @topics = Topic.all.sort_by_id
    end

    def set_sidebar_topics
      if logged_in?(:site_admin) 
        @sidebar_topics = Topic.with_blogs
      else
        @sidebar_topics = Topic.with_blogs_published
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title)
    end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def unclassify_blog blog
    blog.update!(topic_id: 1)
  end

end

app/views/topics/_topic_form.html.erb
<%= form_for(topic) do |t| %>
  
  <div class="form-group">
    <%= t.label :title  %>
    <%= t.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= t.submit "Submit", class: 'btn btn-primary' %>
    <%= link_to "Cancel", topics_path, class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h3>Edit Topic</h3>

<%= form_for(@topic) do |t| %>
  
  <div class="form-group">
    <%= t.label :title  %>
    <%= t.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= t.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/topics/index.html.erb
<h3>Topics</h3>

<table class="form-group topics-form">
  <tr>
<!--     <th>ID</th> -->
    <th> Topic </th>
    <th>Blogs</th>
    <th></th>
  </tr>
  

  <% @topics.drop(1).each do |t| %>
    <tr>
      <!-- <td><div class="topics-item centered"><%= t.id %></div></td> -->
      <td><div class="topics-item"> <%= t.title %> </div></td>
      <td><div class="topics-item centered"><%= t.blogs.count %></div></td>
      <td>
        <div class="edit-delete">
          <%= link_to 'Edit Topic', edit_topic_path(t), class: 'btn btn-primary' %>
          <%= link_to 'Delete Topic', topic_path(t), method: 'delete', data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %>
        </div>
      </td>
    </tr>
  <% end %>
  <tr>
   <!--  <td><div class="topics-item centered first-topic"><%= @topics.first.id %></div></td> -->
    <td><div class="topics-item first-topic"> <%= @topics.first.title %> </div></td>
    <td><div class="topics-item centered first-topic"><%= @topics.first.blogs.count %></div></td>
    <td></td>
  </tr>

</table>


<%= link_to 'Add new Topic', new_topic_path, class: 'btn btn-primary'%>

app/views/topics/new.html.erb
<h3>New Topic</h3>

<%= render 'topic_form', topic: @topic %>

app/views/topics/show.html.erb
<h1>Topic: <%= @topic.title %></h1>
<%= paginate @topic_blogs %>
<%= render @topic_blogs, layout: 'blog' %>
<%= paginate @topic_blogs %>