config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :edit, :show, :update, :new, :create, :destroy]


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios do
    put :sort, on: :collection
  end
  
  get 'angular-items', to: 'portfolios#angular'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech_news', to: 'pages#tech_news'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end


  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
  
end

app/views/shared/_application_footer.html.erb
  <div class="mastfoot">
    <div class="inner">
      <p class="app-footer"><%= copyright_generator %></p>
    </div>
  </div>

app/views/shared/_application_nav.html.erb
    <div class="masthead clearfix">
      <div class="inner">
        <h3 class="masthead-brand">Jan Meckelholt</h3>
        <nav class="nav nav-masthead app-nav">
          <%= nav_helper('nav-link', 'span') %>
          <%= login_helper('nav-link') %>
        </nav>
      </div>
    </div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p class="app-footer"><%= copyright_generator %></p>
  <p><a href="#">Back to the top</a></p>

</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-masthead">
  <div class="container">
    <div class="row">
      
        <div class="col-sm-8">
        <nav class="nav blog-nav">
          <%= nav_helper('nav-link', 'span') %>
        </nav>
        </div>   
        
        <div class="col-sm-4">
        <nav class="nav blog-nav">
          <%= login_helper('nav-link') %>
        </nav>
        </div>
    
    </div>
  </div>
</div>
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Blogs</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="sidebar-module sidebar-module-inset">
  <h4>About</h4>
  <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
</div>

<div class="sidebar-module">
  <h4>Topics:</h4>
  <% @sidebar_topics.each do |topic| %>
    <p><%= link_to topic.title, topic_path(topic.id) %></p>
  <% end %>
</div>


<div class="sidebar-module">
  <h4>Elsewhere</h4>
  <ol class="list-unstyled social-links">
    <li><a href="#"><%= fa_icon "github" %></a></li>
    <li><a href="#"><%= fa_icon "facebook" %></a></li>
    <li><a href="#"><%= fa_icon "twitter" %></a></li>
  </ol>
  <p><%= source_helper("main") %></p>
</div>

app/views/shared/_nav.html.erb
<%if style  == "text-white + li" %>
  <li><%= link_to "Home", root_path, class: "text-white" %></li>
  <li><%= link_to "About", about_path, class: "text-white" %></li>
  <li><%= link_to "Contact", contact_path, class: "text-white" %></li>
  <li><%= link_to "Blog", blogs_path, class: "text-white" %></li>
  <li><%= link_to "Portfolio", portfolios_path, class: "text-white" %></li>
<% else %>
  <%= link_to "Home", root_path, class: style %>
  <%= link_to "About", about_path, class: style %>
  <%= link_to "Contact", contact_path, class: style %>
  <%= link_to "Blog", blogs_path, class: style %>
  <%= link_to "Portfolio", portfolios_path, class: style %>
<% end %>

app/views/shared/_portfolio_abstract.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    
    <div class="portfolio-abstract-btn">
 
      <%= link_to 'Find out more about me!', about_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>    
    </div>


  </div>
</section>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p><%= source_helper("portfolio") %></p>
    <p class="float-right"><a href="#">Back to top</a></p>
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_header.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">My Portfolio</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Contact</h4>
        <ul class="list-unstyled">
          <%= nav_helper('text-white', 'li') %>
          <li class="portfolio-abstract-li"><%= login_helper("text-white") %></li>
       
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Jan Meckelholt</a>
 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>